SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `words1` (
  `id` int(11) NOT NULL,
  `word` varchar(256) NOT NULL,
  `count` int(11) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `words2` (
  `id` int(11) NOT NULL,
  `word` varchar(256) NOT NULL,
  `count` int(11) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `words3` (
  `id` int(11) NOT NULL,
  `word` varchar(256) NOT NULL,
  `count` int(11) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `words1`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `word` (`word`);

ALTER TABLE `words2`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `word` (`word`);

ALTER TABLE `words3`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `word` (`word`);


ALTER TABLE `words1`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `words2`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `words3`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
